language: objective-c
xcode_project: ZNotification.xcodeproj # path to your xcodeproj folder
xcode_scheme: ZNotification


script:
- 'if [ "$TRAVIS_BRANCH" == "develop" ]; then
    xcodebuild -project ZNotification.xcodeproj -scheme ZNotification -sdk "iphonesimulator10.0" -destination "OS=9.0,name=iPhone 6" -configuration ReleaseCandidate ONLY_ACTIVE_ARCH=NO;
else
    xcodebuild -project ZNotification.xcodeproj -scheme ZNotification -sdk "iphonesimulator10.0" -destination "OS=9.0,name=iPhone 6" -configuration FeatureCandidate ONLY_ACTIVE_ARCH=NO;
fi'
